export default function LeadsInspectionPage() {
  return (
    <div className="flex flex-col h-full w-full p-margin-page">
      <div className="max-w-container-max mx-auto space-y-stack-lg w-full">
        {/* Page Header */}
        <div>
          <h2 className="font-display-xl text-display-xl text-on-surface mb-2">Lead Quality Control</h2>
          <p className="font-body-base text-body-base text-on-surface-variant max-w-2xl">Inspect, verify, and route incoming leads generated by your active recipes. Approve high-quality prospects to push them directly into active campaigns.</p>
        </div>

        {/* Control Bar (Filters) */}
        <div className="bg-surface-container-lowest rounded-lg border border-outline-variant shadow-sm p-4 flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-4 flex-wrap">
            <div className="flex items-center gap-2 bg-surface-container-low px-3 py-1.5 rounded border border-transparent focus-within:border-secondary focus-within:bg-surface-container-lowest transition-colors">
              <span className="material-symbols-outlined text-outline text-[18px]">domain</span>
              <input className="bg-transparent border-none p-0 font-body-sm text-body-sm text-on-surface focus:ring-0 placeholder:text-outline w-40 outline-none" placeholder="Filter by Domain" type="text" />
            </div>
            <div className="flex items-center gap-2 bg-surface-container-low px-3 py-1.5 rounded border border-transparent focus-within:border-secondary focus-within:bg-surface-container-lowest transition-colors cursor-pointer">
              <span className="material-symbols-outlined text-outline text-[18px]">score</span>
              <select className="bg-transparent border-none p-0 font-body-sm text-body-sm text-on-surface focus:ring-0 pr-6 cursor-pointer outline-none">
                <option value="">All Scores</option>
                <option value="high">Score &gt; 80</option>
                <option value="med">Score 50-80</option>
              </select>
            </div>
            <div className="flex items-center gap-2 bg-surface-container-low px-3 py-1.5 rounded border border-transparent focus-within:border-secondary focus-within:bg-surface-container-lowest transition-colors cursor-pointer">
              <span className="material-symbols-outlined text-outline text-[18px]">work</span>
              <select className="bg-transparent border-none p-0 font-body-sm text-body-sm text-on-surface focus:ring-0 pr-6 cursor-pointer outline-none">
                <option value="">All Industries</option>
                <option value="saas">SaaS</option>
                <option value="fintech">Fintech</option>
                <option value="ecommerce">E-commerce</option>
              </select>
            </div>
          </div>
          <div className="font-body-sm text-body-sm text-outline-variant font-medium">
            Showing 24 unverified leads
          </div>
        </div>

        {/* Data Table */}
        <div className="bg-surface-container-lowest rounded-lg border border-outline-variant shadow-sm overflow-hidden">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-surface-container-low border-b border-outline-variant">
                <th className="py-3 px-4 font-label-caps text-label-caps text-on-surface-variant w-[25%]">Name / Company</th>
                <th className="py-3 px-4 font-label-caps text-label-caps text-on-surface-variant w-[10%]">Score</th>
                <th className="py-3 px-4 font-label-caps text-label-caps text-on-surface-variant w-[15%]">Domain</th>
                <th className="py-3 px-4 font-label-caps text-label-caps text-on-surface-variant w-[15%]">Industry</th>
                <th className="py-3 px-4 font-label-caps text-label-caps text-on-surface-variant w-[25%]">Key Insight</th>
                <th className="py-3 px-4 font-label-caps text-label-caps text-on-surface-variant w-[10%] text-right">Action</th>
              </tr>
            </thead>
            <tbody className="font-body-sm text-body-sm">
              {/* Row 1 */}
              <tr className="border-b border-outline-variant last:border-0 hover:bg-surface-container-low transition-colors group">
                <td className="py-3 px-4">
                  <div className="font-semibold text-on-secondary-fixed">Sarah Jenkins</div>
                  <div className="text-outline-variant text-[12px] mt-0.5">VP of Growth, TechNova</div>
                </td>
                <td className="py-3 px-4">
                  <div className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded bg-tertiary-fixed-dim/20 text-on-tertiary-container font-medium">
                    <span className="material-symbols-outlined text-[14px]">trending_up</span>
                    94
                  </div>
                </td>
                <td className="py-3 px-4 text-on-surface-variant">technova.io</td>
                <td className="py-3 px-4 text-on-surface-variant">Enterprise SaaS</td>
                <td className="py-3 px-4 text-on-surface-variant">
                  <div className="truncate max-w-[250px]" title="Recently raised Series B, actively hiring marketing roles.">Recently raised Series B, actively hiring marketing roles.</div>
                </td>
                <td className="py-3 px-4 text-right">
                  <div className="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button className="w-8 h-8 rounded-full bg-surface-container-highest text-on-surface hover:text-error hover:bg-error-container transition-colors flex items-center justify-center" title="Reject">
                      <span className="material-symbols-outlined text-[18px]">close</span>
                    </button>
                    <button className="w-8 h-8 rounded-full bg-surface-container-highest text-on-surface hover:text-on-tertiary-container hover:bg-tertiary-fixed-dim/30 transition-colors flex items-center justify-center" title="Approve">
                      <span className="material-symbols-outlined text-[18px]">check</span>
                    </button>
                  </div>
                </td>
              </tr>

              {/* Row 2 */}
              <tr className="border-b border-outline-variant last:border-0 hover:bg-surface-container-low transition-colors group">
                <td className="py-3 px-4">
                  <div className="font-semibold text-on-secondary-fixed">Marcus Thorne</div>
                  <div className="text-outline-variant text-[12px] mt-0.5">Founder, BuildFast</div>
                </td>
                <td className="py-3 px-4">
                  <div className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded bg-surface-variant text-on-surface-variant font-medium">
                    <span className="material-symbols-outlined text-[14px]">horizontal_rule</span>
                    72
                  </div>
                </td>
                <td className="py-3 px-4 text-on-surface-variant">buildfast.dev</td>
                <td className="py-3 px-4 text-on-surface-variant">DevTools</td>
                <td className="py-3 px-4 text-on-surface-variant">
                  <div className="truncate max-w-[250px]" title="Attended recent webinar on automation, high engagement.">Attended recent webinar on automation, high engagement.</div>
                </td>
                <td className="py-3 px-4 text-right">
                  <div className="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button className="w-8 h-8 rounded-full bg-surface-container-highest text-on-surface hover:text-error hover:bg-error-container transition-colors flex items-center justify-center" title="Reject">
                      <span className="material-symbols-outlined text-[18px]">close</span>
                    </button>
                    <button className="w-8 h-8 rounded-full bg-surface-container-highest text-on-surface hover:text-on-tertiary-container hover:bg-tertiary-fixed-dim/30 transition-colors flex items-center justify-center" title="Approve">
                      <span className="material-symbols-outlined text-[18px]">check</span>
                    </button>
                  </div>
                </td>
              </tr>

              {/* Row 3 */}
              <tr className="border-b border-outline-variant last:border-0 hover:bg-surface-container-low transition-colors group bg-surface-container-lowest/50">
                <td className="py-3 px-4">
                  <div className="font-semibold text-on-secondary-fixed">Elena Rostova</div>
                  <div className="text-outline-variant text-[12px] mt-0.5">CMO, FinSecure</div>
                </td>
                <td className="py-3 px-4">
                  <div className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded bg-error-container/50 text-error font-medium">
                    <span className="material-symbols-outlined text-[14px]">warning</span>
                    45
                  </div>
                </td>
                <td className="py-3 px-4 text-on-surface-variant">finsecure.net</td>
                <td className="py-3 px-4 text-on-surface-variant">Fintech</td>
                <td className="py-3 px-4 text-on-surface-variant">
                  <div className="truncate max-w-[250px]" title="Missing direct contact info, generic info@ email found.">Missing direct contact info, generic info@ email found.</div>
                </td>
                <td className="py-3 px-4 text-right">
                  <div className="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button className="w-8 h-8 rounded-full bg-surface-container-highest text-on-surface hover:text-error hover:bg-error-container transition-colors flex items-center justify-center" title="Reject">
                      <span className="material-symbols-outlined text-[18px]">close</span>
                    </button>
                    <button className="w-8 h-8 rounded-full bg-surface-container-highest text-on-surface hover:text-on-tertiary-container hover:bg-tertiary-fixed-dim/30 transition-colors flex items-center justify-center" title="Approve">
                      <span className="material-symbols-outlined text-[18px]">check</span>
                    </button>
                  </div>
                </td>
              </tr>

              {/* Row 4 */}
              <tr className="border-b border-outline-variant last:border-0 hover:bg-surface-container-low transition-colors group">
                <td className="py-3 px-4">
                  <div className="font-semibold text-on-secondary-fixed">David Chen</div>
                  <div className="text-outline-variant text-[12px] mt-0.5">Director of Sales, Apex Logistics</div>
                </td>
                <td className="py-3 px-4">
                  <div className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded bg-tertiary-fixed-dim/20 text-on-tertiary-container font-medium">
                    <span className="material-symbols-outlined text-[14px]">trending_up</span>
                    88
                  </div>
                </td>
                <td className="py-3 px-4 text-on-surface-variant">apexlogistics.com</td>
                <td className="py-3 px-4 text-on-surface-variant">Supply Chain</td>
                <td className="py-3 px-4 text-on-surface-variant">
                  <div className="truncate max-w-[250px]" title="Competitor contract expiring in 3 months based on intent data.">Competitor contract expiring in 3 months based on intent data.</div>
                </td>
                <td className="py-3 px-4 text-right">
                  <div className="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button className="w-8 h-8 rounded-full bg-surface-container-highest text-on-surface hover:text-error hover:bg-error-container transition-colors flex items-center justify-center" title="Reject">
                      <span className="material-symbols-outlined text-[18px]">close</span>
                    </button>
                    <button className="w-8 h-8 rounded-full bg-surface-container-highest text-on-surface hover:text-on-tertiary-container hover:bg-tertiary-fixed-dim/30 transition-colors flex items-center justify-center" title="Approve">
                      <span className="material-symbols-outlined text-[18px]">check</span>
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
